// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBofEEfDePwiKTOFicOi6kac9wgCMc-MXQ',
    appId: '1:744256673317:web:774c9210d5a1d9bc0e51cc',
    messagingSenderId: '744256673317',
    projectId: 'map-mandarin-smart',
    authDomain: 'map-mandarin-smart.firebaseapp.com',
    storageBucket: 'map-mandarin-smart.firebasestorage.app',
    measurementId: 'G-PWN71X7SXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrgIgWqmisXe63zH54OQyinC86F0Gpl1o',
    appId: '1:744256673317:android:f1df264588a096960e51cc',
    messagingSenderId: '744256673317',
    projectId: 'map-mandarin-smart',
    storageBucket: 'map-mandarin-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL8CD-ui0jVUSmPvtvzhw570PlYx7BHB0',
    appId: '1:744256673317:ios:b8c1c0dae13e4ebc0e51cc',
    messagingSenderId: '744256673317',
    projectId: 'map-mandarin-smart',
    storageBucket: 'map-mandarin-smart.firebasestorage.app',
    iosBundleId: 'com.mandarinsmart.mandarinSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL8CD-ui0jVUSmPvtvzhw570PlYx7BHB0',
    appId: '1:744256673317:ios:b8c1c0dae13e4ebc0e51cc',
    messagingSenderId: '744256673317',
    projectId: 'map-mandarin-smart',
    storageBucket: 'map-mandarin-smart.firebasestorage.app',
    iosBundleId: 'com.mandarinsmart.mandarinSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBofEEfDePwiKTOFicOi6kac9wgCMc-MXQ',
    appId: '1:744256673317:web:0ee69f59c8f0ca580e51cc',
    messagingSenderId: '744256673317',
    projectId: 'map-mandarin-smart',
    authDomain: 'map-mandarin-smart.firebaseapp.com',
    storageBucket: 'map-mandarin-smart.firebasestorage.app',
    measurementId: 'G-TPL23TPYQE',
  );
}
